---
name: triton_example
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cuda-cudart
  - cudf
  - cuml
  - cupy
  - jupyter
  - kaggle
  - matplotlib
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn<1.2.0
  - pip:
      - tritonclient[all]
      - protobuf==3.20.1
      - xgboost
