---
name: triton_example
channels:
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - cudatoolkit=12.2
  - cudf=24.10
  - cuml=24.10
  - cupy
  - jupyter
  - kaggle
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.8
  - scikit-learn<1.2.0
  - pip:
      - tritonclient[all]
      - protobuf==3.20.1
      - xgboost>=1.5,<1.6
